### ISSUE TITLE
404 page not found

### ISSUE THREAD

**Issue by justcop** [knadh/pfxsigner#3]
I have the command line working fine (although found the instructions quite confusing, I'll suggest an edit to those)
However when trying to use the API mode, the server seems to set up OK and I get the following confirmation when accesing the local port:

{"status":"success","data":"Welcome to pfxsigner. Send a request to /document for document signing."}

However when attempting to use the /document subpage the only response I get is a 404 error.

One thing to add is that I did have to change the port in the main.go file, as my port 8000 was already in use. Perhaps this is the cause for the error.

**Comment by knadh** [comment]
You don't have to edit the Go file and can instead use the `--address` flag instead. Eg: `./pfxsigner server --address ":9050"`

`/document` only accepts a POST request with two fields `props` (JSON string) and `file` (multipart file upload) as described in the README. Sending a GET request will throw a 404.
